Added building markers to the leaflet map
PayneMeade/T.E.A.M.-BucView pull request #16
Opened 2023-03-22 20:44 UTC by cawalton910

2023-03-22 20:48 UTC, adamsrodgers approved these changes

2023-03-27 20:32 UTC, Austinhamilton1 approved these changes

2023-03-27 20:36 UTC, Austinhamilton1 requested changes
Lat and Long are backwards

2023-03-29 19:27 UTC, Austinhamilton1 approved these changes

2023-03-29 19:27 UTC, merged